version: 2.0.1

jenkins:
  environment:
    app_name: "${APP_NAME}"
    image_name: "${IMAGE_NAME}"
    container_name: "${CONTAINER_NAME}"
    venv_dir: "${VENV_DIR}"

nginx:
  base_path: "C:/Users/80017206/Desktop/6M Intern/app"
  caller_application: "python app.py"

  server:
    listen: 80
    server_name: localhost

    location_root:
      proxy_pass: "http://127.0.0.1:5000"
      proxy_set_header_Host: "$host"
      proxy_set_header_X_Real_IP: "$remote_addr"
      proxy_set_header_X_Forwarded_For: "$proxy_add_x_forwarded_for"
      proxy_set_header_X_Forwarded_Proto: "$scheme"

    location_static:
      alias: "C:/Users/80017206/Desktop/6M Intern/app/static/"
      autoindex: off